services:
  avito_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONN=postgres://postgres:postgres@postgres:5432/avito_test?sslmode=disable
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avito_test
      - SERVER_PORT=8080
      - JWT_SECRET_KEY=secret
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - ./migrations:/migrations
      - ./database/avito_test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avito_test
    restart: unless-stopped
